POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjQwODE1NDIsInVzZXJJZCI6MX0.QoBEWBecCH-g2zjkA6-XOY11rVfHucUEtovbQuUb6sk

{
    "name":"Test event",
    "description":"Test an event",
    "location":"A test location",
    "datetime":"2025-01-01T15:30:00.000Z"
}